<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusinessInterfase\BusinessInterfase.csproj" />
    <ProjectReference Include="..\BusinessType\BusinessType.csproj" />
    <ProjectReference Include="..\DataInterfase\DataInterfase.csproj" />
  </ItemGroup>

</Project>
